[package]
name = "pidif"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
poppler = "0.3.2"
cairo-rs = "0.15.12"
glib-macros = "0.15.11"
gio = "0.15.12"
glib = "0.15.12"
gtk4 = "0.4.8"
